name: faker_app_flutter_firebase
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.8
  equatable: 2.0.5
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  firebase_ui_auth: ^1.2.2
  cloud_firestore: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
